import {
  Shield,
  Monitor,
  Wrench,
  FlaskConical,
  ClipboardCheck,
  AlertTriangle,
  Thermometer,
  Factory,
  GraduationCap,
  Layers,
  GitBranch,
  Database,
  Microscope,
  ScanLine,
  HeartPulse,
  Snowflake,
  Package,
} from "lucide-react";

export const allServices = [
  { icon: Wrench, title: "Process Validation", desc: "Prospective, concurrent and retrospective process validation for pharmaceutical manufacturing including solid dosage forms, sterile products, and biologics. Full VMP, URS, DQ, IQ, OQ, PQ documentation." },
  { icon: Monitor, title: "Computer System Validation (CSV)", desc: "GAMP 5-compliant validation for ERP (SAP), LIMS, MES, DCS, SCADA, QMS, and all GxP-critical computerized systems. 21 CFR Part 11 and Annex 11 compliant deliverables." },
  { icon: Shield, title: "Equipment Qualification (IQ/OQ/PQ)", desc: "Design, Installation, Operational, and Performance Qualification for manufacturing equipment, laboratory instruments, clean rooms, HVAC, and utility systems." },
  { icon: FlaskConical, title: "Method Validation", desc: "Analytical method validation per ICH Q2(R1) - specificity, linearity, range, accuracy, precision (repeatability, intermediate precision, reproducibility), LOD, LOQ, and robustness studies." },
  { icon: ClipboardCheck, title: "Regulatory Compliance & Audits", desc: "Pre-approval inspections, mock FDA/EMA audits, gap analysis, CAPA management, and remediation support. Regulatory submission dossiers and validation summaries." },
  { icon: AlertTriangle, title: "Risk Management", desc: "ICH Q9-based risk assessments, FMEA, HACCP, and risk-based validation strategies. Risk register development and lifecycle risk management programs." },
  { icon: Thermometer, title: "Cleaning Validation", desc: "Dedicated cleaning validation programs with swab/rinse sampling, worst-case product calculations, acceptance criteria determination, and analytical testing support." },
  { icon: Factory, title: "Facility & Utility Validation", desc: "Clean room qualification, HVAC validation, purified water and WFI systems, compressed air, nitrogen - complete utility validation packages." },
  { icon: GraduationCap, title: "Training & Workshops", desc: "Onsite and virtual training programs on GMP, GDP, process validation lifecycle, CSV/GAMP 5, risk management, data integrity, and regulatory compliance." },
  { icon: Layers, title: "CQV & Capital Project Support", desc: "End-to-end commissioning, qualification, and validation for greenfield and brownfield projects - URS through PQ, turnover packages, and seamless handover to operations." },
  { icon: GitBranch, title: "Tech Transfer & Scale-Up", desc: "Process transfers between sites or scales, comparability protocols, bridging validation, and PPQ strategy updates to maintain product quality and regulatory alignment." },
  { icon: Microscope, title: "Sterility Assurance & Aseptic Validation", desc: "Media fill simulations, aseptic process simulations, smoke studies, EM program support, and Annex 1-aligned contamination control strategy documentation." },
  { icon: Package, title: "Packaging Validation", desc: "Primary and secondary packaging qualifications, shelf-life supporting studies coordination, container-closure integrity considerations, and line-clearance SOP alignment." },
  { icon: ScanLine, title: "Serialization & Track-and-Trace", desc: "DSCSA / EU FMD readiness, Level 3-4 integration support, PI verification, error-handling SOPs, and validation evidence for serialization and aggregation lines." },
  { icon: Database, title: "Data Integrity & ALCOA+", desc: "Data governance gap assessments, audit trail reviews, ALCOA+ remediation, MHRA/FDA data integrity expectation mapping, and lab/instrument data flow documentation." },
  { icon: Snowflake, title: "Temperature Mapping & Cold Chain", desc: "Warehouse, freezer, refrigerator, incubator, and transport mapping; seasonal re-verification planning; and cold-chain validation for APIs, DP, and clinical supplies." },
  { icon: HeartPulse, title: "Medical Device QMS & Validation", desc: "ISO 13485 and 21 CFR Part 820 design controls support, process validation for device manufacturing, and software in medical device (SiMD) lifecycle documentation." },
];
